Fixed an issue with the start of the file resulting in an error
The first line of "---" causes kubectl apply to return the error:
error: no objects passed to apply
due to the fact nothing comes before that --- and it reads that as an empty file.